@description('The name of the log analytics workspace. If set, it overrides the name generated by the template.')
param logAnalyticsWorkspaceName string

module logsModule 'app_environment/logs.bicep' = {
  name: 'logs'
  params: {
    logAnalyticsWorkspaceName: logAnalyticsWorkspaceName
  }
}
