#!/usr/bin/env bash
set -e

source ./common/set_env
source ./common/fetch_and_set_secret_env AVENIR_NM_DB_PASSWORD

./common/azure_login

export AZURE_HINT_CR_SERVER=$(az acr show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query loginServer --output tsv)
export AZURE_HINT_CR_USERNAME=$(az acr credential show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query username --output tsv)
export AZURE_HINT_CR_PASSWORD=$(az acr credential show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query passwords[0].value --output tsv)

az stack group create \
  --name $HINT_DEPLOYMENT_STACK \
  --resource-group $HINT_RESOURCE_GROUP \
  --parameters production.bicepparam \
  --action-on-unmanage deleteResources \
  --deny-settings-mode none
