#!/usr/bin/env bash
set -e

source ./common/set_env
source ./common/fetch_and_set_secret_env AVENIR_NM_DB_PASSWORD

./common/azure_login

export AZURE_HINT_CR_SERVER=$(az acr show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query loginServer --output tsv)
export AZURE_HINT_CR_USERNAME=$(az acr credential show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query username --output tsv)
export AZURE_HINT_CR_PASSWORD=$(az acr credential show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query passwords[0].value --output tsv)

# Find the latest sha for this tag in ghcr
ARM_PARAMS=$(az bicep build-params --file "production.bicepparam" --stdout)

get_param() {
    local PARAM_NAME="$1"
    echo "$ARM_PARAMS" | jq -r ".parametersJson | fromjson | .parameters.${PARAM_NAME}.value"
}

get_sha() {
  local IMAGE_NAME="$1"
  docker manifest inspect $IMAGE_NAME | jq -r '.manifests[0].digest'
}

get_tag() {
  echo $1 | cut -d':' -f2
}

get_repo_path() {
  echo $1 | cut -d':' -f1
}

HINTR_WORKER_IMAGE=$(get_param "hintrWorkerImage")
HINTR_WORKER_SHA=$(get_sha $HINTR_WORKER_IMAGE)
HINTR_WORKER_REPO_PATH=$(get_repo_path $HINTR_WORKER_IMAGE)

az deployment group create \
  --resource-group $HINT_RESOURCE_GROUP \
  --template-file bicep/worker_job.bicep \
  --parameters location=$(get_param "location") \
  containerAppsEnvironmentName=$(get_param "containerAppsEnvironmentName") \
  workloadProfile=$(get_param "workerWorkloadProfileName") \
  redisName=$(get_param "redisName") \
  hintrWorkerImage=$HINTR_WORKER_REPO_PATH@$HINTR_WORKER_SHA
