#!/usr/bin/env bash
set -e

source ./common/set_env
source ./common/fetch_and_set_secret_env AVENIR_NM_DB_PASSWORD

./common/azure_login

az stack group create \
  --name $BACKUP_DEPLOYMENT_STACK \
  --resource-group $HINT_RESOURCE_GROUP \
  --template-file bicep/backup.bicep \
  --parameters params/production/backup.bicepparam \
  --action-on-unmanage deleteResources \
  --deny-settings-mode none
