#!/usr/bin/env bash
set -e

# Specify your tenant ID here
TENANT_ID="28927a05-4ff6-441e-88d9-16f2b63f4884"

source ./common/fetch_and_set_env_vars AVENIR_NM_DB_PASSWORD

# Function to check if the user is logged in
check_login() {
  az account show &>/dev/null
  return $?
}

# Check if the user is logged in
if check_login; then
  echo "You are already logged in to Azure."
else
  echo "You are not logged in to Azure. Logging in now..."
  az login --tenant $TENANT_ID
  if [ $? -eq 0 ]; then
    echo "Azure login successful."
  else
    echo "Azure login failed. Please check your credentials and try again."
  fi
fi

export HINT_DEPLOYMENT_STACK="hint-stack"
export HINT_RESOURCE_GROUP="nmHint-RG"
export HINT_CR="nmHintCR"

export AZURE_HINT_CR_SERVER=$(az acr show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query loginServer --output tsv)
export AZURE_HINT_CR_USERNAME=$(az acr credential show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query username --output tsv)
export AZURE_HINT_CR_PASSWORD=$(az acr credential show --name $HINT_CR --resource-group $HINT_RESOURCE_GROUP --query passwords[0].value --output tsv)

az stack group create \
  --name $HINT_DEPLOYMENT_STACK \
  --resource-group $HINT_RESOURCE_GROUP \
  --parameters production.bicepparam \
  --action-on-unmanage deleteResources \
  --deny-settings-mode none
