#!/usr/bin/env bash
set -e

source ./common/set_env
source ./common/fetch_and_set_secret_env AVENIR_NM_DB_PASSWORD

./common/azure_login

# Find the latest sha for this tag in ghcr
ARM_PARAMS=$(az bicep build-params --file "production.bicepparam" --stdout)

get_param() {
    local PARAM_NAME="$1"
    echo "$ARM_PARAMS" | jq -r ".parametersJson | fromjson | .parameters.${PARAM_NAME}.value"
}

get_sha() {
  local IMAGE_NAME="$1"
  docker manifest inspect $IMAGE_NAME | jq -r '.manifests[0].digest'
}

get_tag() {
  echo $1 | cut -d':' -f2
}

get_repo_path() {
  echo $1 | cut -d':' -f1
}

HINTR_CONTAINER_APP=$(get_param "hintrName")
HINTR_IMAGE=$(get_param "hintrImage")
HINTR_TAG=$(get_tag $HINTR_IMAGE)
HINTR_SHA=$(get_sha $HINTR_IMAGE)
HINTR_REPO_PATH=$(get_repo_path $HINTR_IMAGE)

HINTR_WORKER_CONTAINER_APP=$(get_param "hintrWorkerName")
HINTR_WORKER_IMAGE=$(get_param "hintrWorkerImage")
HINTR_WORKER_SHA=$(get_sha $HINTR_WORKER_IMAGE)
HINTR_WORKER_TAG=$(get_tag $HINTR_WORKER_IMAGE)
HINTR_WORKER_REPO_PATH=$(get_repo_path $HINTR_WORKER_IMAGE)

echo "Updating hintr app"
az containerapp update \
  -n $HINTR_CONTAINER_APP \
  -g $HINT_RESOURCE_GROUP \
  --image $HINTR_REPO_PATH@$HINTR_SHA \
  --tags IMAGE_TAG=$HINTR_TAG IMAGE_SHA=$HINTR_SHA \
  -o none
echo "Complete"

echo "Updating hintr workers app"
az containerapp update \
  -n $HINTR_WORKER_CONTAINER_APP \
  -g $HINT_RESOURCE_GROUP \
  --image $HINTR_WORKER_REPO_PATH@$HINTR_WORKER_SHA \
  --tags IMAGE_TAG=$HINTR_WORKER_TAG IMAGE_SHA=$HINTR_WORKER_SHA \
  -o none
echo "Complete"
