#!/usr/bin/env bash
set -e

# Specify your tenant ID here
TENANT_ID="14b292c0-30d6-4933-b442-65f54ff20563"

# Function to check if the user is logged in
check_login() {
  az account show &>/dev/null
  return $?
}

# Check if the user is logged in
if check_login; then
  echo "You are already logged in to Azure."
else
  echo "You are not logged in to Azure. Logging in now..."
  az login --tenant $TENANT_ID
  if [ $? -eq 0 ]; then
    echo "Azure login successful."
  else
    echo "Azure login failed. Please check your credentials and try again."
  fi
fi
