#!/usr/bin/env bash
set -e

export NETWORK_DEPLOYMENT_STACK="network-stack"
export STORAGE_DEPLOYMENT_STACK="storage-stack"
export ENVRIONMENT_DEPLOYMENT_STACK="environment-stack"
export CONTAINERS_DEPLOYMENT_STACK="containers-stack"
export BACKUP_DEPLOYMENT_STACK="backup-stack"
export HINT_RESOURCE_GROUP="nmHint-RG"
export OBSERVABILITY_RESOURCE_GROUP="nmHint-logs-RG"
export HINT_STORAGE_ACCOUNT="naomiappstorage"
